name: recon
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.1=cpu_0
  - absl-py=0.9.0=py36_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py36h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.16.1=h516909a_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.1.1=py_0
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.1=py36he30daa8_0
  - chardet=3.0.4=py36_1003
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.5.0=py_0
  - cmake=3.14.0=h52cb24c_0
  - cryptography=2.9.2=py36h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.23.0=py_0
  - dataclasses=0.8=pyh4f3eec9_6
  - decorator=4.4.2=py_0
  - enum34=1.1.10=py36h9f0ad1d_1
  - expat=2.2.9=he6710b0_2
  - freetype=2.10.2=h5ab3b9f_0
  - future=0.18.2=py36_1
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.31.0=py36h769ab6c_0
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=py_0
  - imagecodecs-lite=2019.12.3=py36h785e9b2_1
  - imageio=2.9.0=py_0
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py36hdb11119_0
  - krb5=1.18.2=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.4=h8b12597_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=he6710b0_1
  - magma-cuda102=2.5.2=1
  - markdown=3.2.2=py_0
  - matplotlib-base=3.3.1=py36h5ffbc53_0
  - mkl=2020.1=217
  - mkl-include=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.10.0=py36hfd86e86_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py36_0
  - openssl=1.1.1l=h7f8727e_0
  - pathlib=1.0.1=py36h9f0ad1d_2
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.2.2=py36_0
  - protobuf=3.12.4=py36h831f99a_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.7.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pywavelets=1.1.1=py36h785e9b2_1
  - pyyaml=5.3.1=py36h7b6447c_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rhash=1.3.8=h1ba5d50_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-image=0.17.2=py36h830a2c2_1
  - scipy=1.5.0=py36h0b6359f_0
  - setuptools=49.6.0=py36_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboard=2.3.0=py_0
  - tensorboard-plugin-wit=1.6.0=pyh9f0ad1d_0
  - tifffile=2019.7.26.2=py36_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchaudio=0.7.0=py36
  - tornado=6.0.4=py36h8c4c3a4_1
  - tqdm=4.48.2=pyh9f0ad1d_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - joblib==0.16.0
    - nibabel==3.1.1
    - opencv-python==4.4.0.42
    - packaging==20.4
    - pandas==1.1.0
    - pympler==0.8
    - pytorch-lightning==0.7.5
    - pytz==2020.1
    - runstats==1.8.0
    - scikit-learn==0.23.2
    - seaborn==0.11.0
    - tensorboardx==1.4
    - threadpoolctl==2.1.0
    - timm==0.4.12
    - torchvision==0.4.2
prefix: /home/pengfei/anaconda3/envs/recon
